// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Urbanflow.src.backend.db;

#nullable disable

namespace Urbanflow.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260215132702_SmallFix")]
    partial class SmallFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Urbanflow.src.backend.models.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GtfsFeedId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GtfsFeedId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("GtfsFeedId");

                    b.ToTable("Workflows", (string)null);
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.graph.Edge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FromNodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ToNodeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Edges", (string)null);
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.graph.Graph", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Graphs", (string)null);
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.graph.GraphEdge", b =>
                {
                    b.Property<Guid>("GraphId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EdgeId")
                        .HasColumnType("TEXT");

                    b.HasKey("GraphId", "EdgeId");

                    b.ToTable("GraphEdges", (string)null);
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.graph.GraphNode", b =>
                {
                    b.Property<Guid>("GraphId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("TEXT");

                    b.HasKey("GraphId", "NodeId");

                    b.ToTable("GraphNodes", (string)null);
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.graph.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StopId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Nodes", (string)null);
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.gtfs.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Agency_Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FareURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GtfsFeedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GtfsFeedId");

                    b.ToTable("Agencies", (string)null);
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.gtfs.Calendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Friday")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GtfsFeedId")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Mask")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Monday")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Saturday")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sunday")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Thursday")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GtfsFeedId");

                    b.ToTable("Calendars", (string)null);
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.gtfs.CalendarDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExceptionType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GtfsFeedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GtfsFeedId");

                    b.ToTable("CalendarDates", (string)null);
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.gtfs.FeedInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FeedInfos", (string)null);
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.gtfs.GtfsFeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublisherName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublisherUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GtfsFeeds", (string)null);
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.gtfs.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgencyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GtfsFeedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TextColor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GtfsFeedId");

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.gtfs.Shape", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("DistanceTravelled")
                        .HasColumnType("REAL");

                    b.Property<Guid>("GtfsFeedId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<uint>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShapeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GtfsFeedId");

                    b.ToTable("Shapes", (string)null);
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.gtfs.Stop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GtfsFeedId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<int?>("LocationType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NodeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentStation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WheelchairBoarding")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GtfsFeedId");

                    b.ToTable("Stops", (string)null);
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.gtfs.StopTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArrivalTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DropOffType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GtfsFeedId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PickupType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShapeDistTravelled")
                        .HasColumnType("TEXT");

                    b.Property<string>("StopHeadsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("StopSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GtfsFeedId");

                    b.ToTable("StopTimes", (string)null);
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.gtfs.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AccessibilityType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlockId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GtfsFeedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShapeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GtfsFeedId");

                    b.ToTable("Trips", (string)null);
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.Workflow", b =>
                {
                    b.HasOne("Urbanflow.src.backend.models.City", "City")
                        .WithMany("Workflows")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Urbanflow.src.backend.models.gtfs.GtfsFeed", "GtfsFeed")
                        .WithMany()
                        .HasForeignKey("GtfsFeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("GtfsFeed");
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.gtfs.Agency", b =>
                {
                    b.HasOne("Urbanflow.src.backend.models.gtfs.GtfsFeed", "GtfsFeed")
                        .WithMany("Agencies")
                        .HasForeignKey("GtfsFeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GtfsFeed");
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.gtfs.Calendar", b =>
                {
                    b.HasOne("Urbanflow.src.backend.models.gtfs.GtfsFeed", "GtfsFeed")
                        .WithMany("Calendars")
                        .HasForeignKey("GtfsFeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GtfsFeed");
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.gtfs.CalendarDate", b =>
                {
                    b.HasOne("Urbanflow.src.backend.models.gtfs.GtfsFeed", "GtfsFeed")
                        .WithMany("CalendarDates")
                        .HasForeignKey("GtfsFeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GtfsFeed");
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.gtfs.Route", b =>
                {
                    b.HasOne("Urbanflow.src.backend.models.gtfs.GtfsFeed", "GtfsFeed")
                        .WithMany("Routes")
                        .HasForeignKey("GtfsFeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GtfsFeed");
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.gtfs.Shape", b =>
                {
                    b.HasOne("Urbanflow.src.backend.models.gtfs.GtfsFeed", "GtfsFeed")
                        .WithMany("Shapes")
                        .HasForeignKey("GtfsFeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GtfsFeed");
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.gtfs.Stop", b =>
                {
                    b.HasOne("Urbanflow.src.backend.models.gtfs.GtfsFeed", "GtfsFeed")
                        .WithMany("Stops")
                        .HasForeignKey("GtfsFeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GtfsFeed");
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.gtfs.StopTime", b =>
                {
                    b.HasOne("Urbanflow.src.backend.models.gtfs.GtfsFeed", "GtfsFeed")
                        .WithMany("StopTimes")
                        .HasForeignKey("GtfsFeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GtfsFeed");
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.gtfs.Trip", b =>
                {
                    b.HasOne("Urbanflow.src.backend.models.gtfs.GtfsFeed", "GtfsFeed")
                        .WithMany("Trips")
                        .HasForeignKey("GtfsFeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GtfsFeed");
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.City", b =>
                {
                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("Urbanflow.src.backend.models.gtfs.GtfsFeed", b =>
                {
                    b.Navigation("Agencies");

                    b.Navigation("CalendarDates");

                    b.Navigation("Calendars");

                    b.Navigation("Routes");

                    b.Navigation("Shapes");

                    b.Navigation("StopTimes");

                    b.Navigation("Stops");

                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
